#!usr/bin/bash

# if bc is not intalled
sudo apt-get update -y
sudo apt-get install -y bc

#create file
nano arguments.sh

#calculate celsius from farenheit
#!/bin/usr/bash

par_f=$1
temp_c=$(echo "scale=2;($par_f - 32) * 5 / 9" | bc)
echo "$par_f farenheit in celsius equals $temp_c"



