#!usr/bin/bash

#check tasks
crontab -l

#setup one with nano
crontab -e
30 2 * * * bash example.sh

#verify it
crontab -l

#Useful pages:
https://crontab.guru/
https://wiki.gentoo.org/wiki/Nano/Guide
