#!/usr/bin/bash

#function to calculate the sum of elements of an array
function sum_loop () {
  local base=0
  
  for i in "$@"
  do
    base=$(echo "$base + $i" | bc)
  done
  
  echo $base
  }
  
  
# Call function with array
test=(1 2 3 4)
echo "sum is $(sum_loop ${test[@]})"
